/MyDetector/nCols 100
/MyDetector/nRows 100
/run/reinitializeGeometry 1
/run/initialize
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm x 1 0 0 manual 45 50 50 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate 10
/MyDetector/isPET 0
/MyDetector/isCherenkov 0
/MyDetector/isCubic_Detector_Demo 0
/MyDetector/isCubic_Detector 0