/vis/open OGL
/vis/viewer/set/projection p
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
#/scale [length] [unit] [direction] [red] [green] [blue] [auto|manual] [xmid] [ymid] [zmid] [unit]
/vis/scene/add/scale 10 cm x 1 0 0 manual 45 50 50 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate 50
# trajectory with Blue is positive charge and Red is negative charge