#Enable command echo
/control/verbose 2

/vis/open OGL 
/vis/drawVolume


#	Trajectory with Blue color is positive charge, Red color is negative charge, Green color is gamma charge, neutrino is yellow
/vis/scene/add/trajectories smooth

#/scale [length] [unit] [direction] [red] [green] [blue] [auto|manual] [xmid] [ymid] [zmid] [unit]
/vis/scene/add/scale 5 cm x 1 0 0 manual -2.5 0 0 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate 20
